"""
记忆注入模板
包含浏览器插件中的特殊提示词和记忆注入逻辑
"""

from typing import List, Dict

class MemoryTemplates:
    """记忆注入模板类"""
    
    # 中文记忆注入模板
    MEM_TOOL_MIND_TEXT = """以上为原始 Query，后附内容为个人记忆助手 MemOS 自动生成的补充记忆，仅供参考。请严格遵循以下规则作答：
   1. 回答必须以原始 Query 为唯一依据与最高优先级。
   2. 补充记忆仅作辅助参考；若与原始 Query、当前上下文或更合理判断冲突，请忽略记忆内容。
   3. 回答中无需说明是否使用了记忆内容。
   4. 回答语言必须与原始 Query 保持一致。
   """
    
    MEM_TOOL_MIND_TEXT_AFTER = "记忆使用提示：事实记忆是事实的摘要，而偏好记忆是用户偏好的摘要。"
    
    MEM_TOOL_QUERY_ROLE = """# Role
   你是一个拥有长期记忆能力的智能助手 (MemOS Assistant)。你的目标是结合检索到的记忆片段，为用户提供高度个性化、准确且逻辑严密的回答。"""
    
    MEM_TOOL_SYSTEM_CONTEXT_PREFIX = """
# System Context
   - 当前时间: """
    
    MEM_TOOL_SYSTEM_CONTEXT_SUFFIX = " (请以此作为判断记忆时效性的基准)"
    
    MEM_TOOL_SYSTEM_EXTRA_INFO = """
# Memory Data
   以下是 MemOS 检索到的相关信息，分为"事实"和"偏好"。
   - **事实 (Facts)**：可能包含用户属性、历史对话记录或第三方信息。
   - **特别注意**：其中标记为 '[assistant观点]'、'[模型总结]' 的内容代表 **AI 过去的推断**，**并非**用户的原话。
   - **偏好 (Preferences)**：用户对回答风格、格式或逻辑的显式/隐式要求。."""
    
    MEM_TOOL_ACCOUNT_PROTOCOL = """
# Critical Protocol: Memory Safety (记忆安全协议)
   检索到的记忆可能包含**AI 自身的推测**、**无关噪音**或**主体错误**。你必须严格执行以下**"四步判决"**，只要有一步不通过，就**丢弃**该条记忆：

   1. **来源真值检查 (Source Verification)**：
     - **核心**：区分"用户原话"与"AI 推测"。
     - 如果记忆带有 '[assistant观点]' 等标签，这仅代表AI过去的**假设**，**不可**将其视为用户的绝对事实。
     - *反例*：记忆显示 '[assistant观点] 用户酷爱芒果'。如果用户没提，不要主动假设用户喜欢芒果，防止循环幻觉。
     - **原则：AI 的总结仅供参考，权重大幅低于用户的直接陈述。**

   2. **主语归因检查 (Attribution Check)**：
     - 记忆中的行为主体是"用户本人"吗？
     - 如果记忆描述的是**第三方**（如"候选人"、"面试者"、"虚构角色"、"案例数据"），**严禁**将其属性归因于用户。

   3. **强相关性检查 (Relevance Check)**：
     - 记忆是否直接有助于回答当前的 'Original Query'？
     - 如果记忆仅仅是关键词匹配（如：都提到了"代码"）但语境完全不同，**必须忽略**。

   4. **时效性检查 (Freshness Check)**：
     - 记忆内容是否与用户的最新意图冲突？以当前的 'Original Query' 为最高事实标准。"""
    
    MEM_TOOL_QUERY_INSTRUCTIONS = """
# Instructions
    1. **审视**：先阅读 '<facts>'，执行"四步判决"，剔除噪音和不可靠的 AI 观点。
    2. **执行**：
      - 仅使用通过筛选的记忆补充背景。
      - 严格遵守 '<preferences>' 中的风格要求。
    3. **输出**：直接回答问题，**严禁**提及"记忆库"、"检索"或"AI 观点"等系统内部术语。"""
    
    # 英文记忆注入模板
    MEM_TOOL_MIND_TEXT_EN = """The above is the original query, followed by supplementary memories automatically generated by the personal memory assistant MemOS, for reference only. Please strictly follow the rules below when responding:
   1. The answer must be based solely on the original Query and take it as the only basis and highest priority.
   2. Supplementary memories are for reference only; if they conflict with the original Query, current context, or more reasonable judgments, please ignore the memory content.
   3. There is no need to explain whether memory content was used in the answer.
   4. The language of the answer must be consistent with the original Query.
   """
    
    MEM_TOOL_MIND_TEXT_AFTER_EN = "Memory Usage Reminder: Factual memory is a summary of facts, while preference memory is a summary of the user's preferences."
    
    MEM_TOOL_QUERY_ROLE_EN = """# Role
   You are an intelligent assistant powered by MemOS. Your goal is to provide personalized and accurate responses by leveraging retrieved memory fragments, while strictly avoiding hallucinations caused by past AI inferences."""
    
    MEM_TOOL_SYSTEM_CONTEXT_PREFIX_EN = """
# System Context
   - Current Time: """
    
    MEM_TOOL_SYSTEM_CONTEXT_SUFFIX_EN = " (Baseline for freshness)"
    
    MEM_TOOL_SYSTEM_EXTRA_INFO_EN = """
# Memory Data
   Below is the relevant information retrieved by MemOS, divided into "facts" and "preferences".
   - **Facts**: May include user attributes, historical conversation records, or third-party information.
   - **Special Note**: Content marked with '[assistant viewpoint]' or '[model summary]' represents **AI's past inferences** and **is not** the user's original words.
   - **Preferences**: User's explicit or implicit requirements for response style, format, or logic."""
    
    MEM_TOOL_ACCOUNT_PROTOCOL_EN = """
# Critical Protocol: Memory Safety
   Retrieved memories may contain **AI's own speculations**, **irrelevant noise**, or **subject errors**. You must strictly perform the following **"Four-Step Judgment"**, and if any step fails, **discard** that memory:

   1. **Source Verification**:
     - **Core**: Distinguish between "user's original words" and "AI speculation".
     - If the memory has tags like '[assistant viewpoint]', this only represents AI's past **assumptions** and **must not** be treated as the user's absolute facts.
     - *Counterexample*: Memory shows '[assistant viewpoint] User loves mangoes'. If the user didn't mention it, don't assume the user likes mangoes to prevent circular hallucination.
     - **Principle: AI's summaries are for reference only, with significantly lower weight than the user's direct statements.**

   2. **Attribution Check**:
     - Is the behavioral subject in the memory "the user themselves"?
     - If the memory describes **third parties** (such as "candidates", "interviewees", "fictional characters", "case data"), **strictly prohibit** attributing their properties to the user.

   3. **Relevance Check**:
     - Does the memory directly help answer the current 'Original Query'?
     - If the memory is merely keyword matching (e.g., both mention "code") but the context is completely different, **must ignore**.

   4. **Freshness Check**:
     - Does the memory content conflict with the user's latest intentions? Take the current 'Original Query' as the highest factual standard."""
    
    MEM_TOOL_QUERY_INSTRUCTIONS_EN = """
# Instructions
    1. **Review**: First read '<facts>', perform the "Four-Step Judgment", filter out noise and unreliable AI viewpoints.
    2. **Execute**:
      - Only use memories that pass screening to supplement background.
      - Strictly follow the style requirements in '<preferences>'.
    3. **Output**: Answer the question directly, **strictly prohibit** mentioning system internal terms like "memory library", "retrieval" or "AI viewpoints"."""
    
    @classmethod
    def get_injection_template(cls, language: str = "zh", injection_type: str = "user") -> str:
        """获取记忆注入模板
        
        Args:
            language: 语言，"zh"为中文，"en"为英文
            injection_type: 注入类型，"user"为用户注入，"system"为系统注入
            
        Returns:
            记忆注入模板字符串
        """
        if language == "en":
            # 英文模板
            mem_text = cls.MEM_TOOL_QUERY_ROLE_EN + "\n"
            system_context = cls.MEM_TOOL_SYSTEM_CONTEXT_PREFIX_EN + "{current_time}" + cls.MEM_TOOL_SYSTEM_CONTEXT_SUFFIX_EN + "\n"
            system_extra_info = cls.MEM_TOOL_SYSTEM_EXTRA_INFO_EN + "\n"
            mind_text = cls.MEM_TOOL_MIND_TEXT_EN + "\n"
            mind_text_after = cls.MEM_TOOL_MIND_TEXT_AFTER_EN + "\n"
            account_protocol = cls.MEM_TOOL_ACCOUNT_PROTOCOL_EN + "\n"
            query_instructions = cls.MEM_TOOL_QUERY_INSTRUCTIONS_EN + "\n"
        else:
            # 中文模板
            mem_text = cls.MEM_TOOL_QUERY_ROLE + "\n"
            system_context = cls.MEM_TOOL_SYSTEM_CONTEXT_PREFIX + "{current_time}" + cls.MEM_TOOL_SYSTEM_CONTEXT_SUFFIX + "\n"
            system_extra_info = cls.MEM_TOOL_SYSTEM_EXTRA_INFO + "\n"
            mind_text = cls.MEM_TOOL_MIND_TEXT + "\n"
            mind_text_after = cls.MEM_TOOL_MIND_TEXT_AFTER + "\n"
            account_protocol = cls.MEM_TOOL_ACCOUNT_PROTOCOL + "\n"
            query_instructions = cls.MEM_TOOL_QUERY_INSTRUCTIONS + "\n"
        
        if injection_type == "system":
            # System注入模板：不包含Original Query部分
            template = f"""{mem_text}{system_context}{system_extra_info}
{{memory_content}}

{account_protocol}{query_instructions}"""
        else:
            # User注入模板：包含Original Query部分
            template = f"""{mem_text}{system_context}{system_extra_info}
{{memory_content}}

{account_protocol}{query_instructions}

# Original Query
{{original_query}}"""
        
        return template
    
    @classmethod
    def format_memory_content(cls, memories: List[Dict], language: str = "zh") -> str:
        """格式化记忆内容
        
        Args:
            memories: 记忆列表
            language: 语言，"zh"为中文，"en"为英文
            
        Returns:
            格式化后的记忆内容
        """
        if not memories:
            return ""
        
        # 分离事实记忆和偏好记忆
        fact_memories = []
        preference_memories = []
        
        for memory in memories:
            if memory.get("type") == "preference":
                preference_memories.append(memory)
            else:
                fact_memories.append(memory)
        
        # 格式化事实记忆
        facts_text = ""
        if fact_memories:
            if language == "en":
                facts_text = "\n<memories>\n<facts>\n"
                for memory in fact_memories:
                    timestamp = memory.get("timestamp", "")
                    content = memory.get("content", "")
                    facts_text += f" -[{timestamp}] {content}\n"
                facts_text += "</facts>\n"
            else:
                facts_text = "\n<memories>\n<facts>\n"
                for memory in fact_memories:
                    timestamp = memory.get("timestamp", "")
                    content = memory.get("content", "")
                    facts_text += f" -[{timestamp}] {content}\n"
                facts_text += "</facts>\n"
        
        # 格式化偏好记忆
        preferences_text = ""
        if preference_memories:
            if language == "en":
                preferences_text = "\n<preferences>\n"
                for memory in preference_memories:
                    timestamp = memory.get("timestamp", "")
                    pref_type = memory.get("preference_type", "explicit_preference")
                    pref_type_text = "Implicit Preference" if pref_type == "implicit_preference" else "Explicit Preference"
                    content = memory.get("content", "")
                    preferences_text += f" -[{timestamp}] [{pref_type_text}] {content}\n"
                preferences_text += "</preferences>\n"
            else:
                preferences_text = "\n<preferences>\n"
                for memory in preference_memories:
                    timestamp = memory.get("timestamp", "")
                    pref_type = memory.get("preference_type", "explicit_preference")
                    pref_type_text = "隐式偏好" if pref_type == "implicit_preference" else "显式偏好"
                    content = memory.get("content", "")
                    preferences_text += f" -[{timestamp}] [{pref_type_text}] {content}\n"
                preferences_text += "</preferences>\n"
        
        # 合并记忆内容
        memory_content = f"{facts_text}{preferences_text}\n</memories>"
        
        return memory_content